// <auto-generated />
using System;
using BookApp.Models.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240117101753_InitialDb")]
    partial class InitialDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.15");

            modelBuilder.Entity("BookApp.Models.Entities.Concrete.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Abstract")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHome")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("PageCount")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Books", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abstract = "'… İyi geceler. Ben prensi olmayan bir Külkedisi’yim. Tokyo’nun neresinde olduğumu biliyor musunuz? Beni bir daha görmeyeceksiniz.'\r\n\r\nYirminci yüzyıl Japon edebiyatının önde gelen yazarlarından, sıradışı hayatıyla da meşhur Osamu Dazai, savaş sonrası Japonya’sının edebiyat çevrelerince tanınmasını sağlayan, kaleme aldığı ilk eserlerden Öğrenci Kız’da Tokyo’nun banliyösünde yaşayan bir genç kızın on iki saatini ironik ve hünerli bir üslupla kaleme alıyor.\r\n\r\nİsimsiz genç kızın, nefret ettiği sabahlardan birine gözlerini açmasıyla başlayıp gece yatağa yattığı anda biten kısa romanda Dazai, artık yitmiş bir dönemin yaygın toplumsal normlarına karşı bireyin duyduğu huzursuzluğu, gençliğin ilk buhranları ve asiliğiyle birleştiriyor. \r\n\r\nÖğrenci Kız, Dazai’nin sonraki çoğu eserinde yer bulacak aykırı kişiliklerin ilk örneklerinden birini görmeyi ve yazarın zihninin derinliklerine yakından bakmayı sağlayacak bir klasik.",
                            CreatedDate = new DateTime(2024, 1, 17, 13, 17, 53, 893, DateTimeKind.Local).AddTicks(3951),
                            ImageUrl = "ogrenci-kiz.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = false,
                            ModifiedDate = new DateTime(2024, 1, 17, 13, 17, 53, 893, DateTimeKind.Local).AddTicks(3953),
                            Name = "Öğrenci Kız",
                            PageCount = 439,
                            Price = 90m,
                            Stock = 4,
                            Url = "ogrenci-kiz-1"
                        },
                        new
                        {
                            Id = 2,
                            Abstract = "Hayvanlardan Tanrılara: Sapiens kitabıyla insan türünün dünyaya nasıl egemen olduğunu anlatan Harari, Homo Deus’ta çarpıcı öngörüleriyle yarınımızı ele alıyor. İnsanlığın ölümsüzlük, mutluluk ve tanrısallık peşindeki yolculuğunu bilim, tarih ve felsefe ışığında incelediği bu çalışmasında, insanın bambaşka bir türe, Homo deus’a evrildiği bir gelecek kurguluyor.\r\n\r\nYola *önemsiz bir hayvan* olarak çıkan Homo sapiens, tanrılar katına ulaşmak uğruna kendi sonunu mu hazırlıyor?\r\n\r\nHomo sapiens nasıl oldu da evrenin insan türünün etrafında döndüğünü iddia eden hümanist öğretiye inandı?\r\n\r\nBu öğreti gündelik yaşantımızı, sanatımızı ve en gizli tutkularımızı nasıl şekillendiriyor?\r\n\r\nİnsanı inekler, tavuklar, şempanzeler ve bilgisayar programlarının tümünden ayıran yüksek zekası ve kudreti dışında herhangi bir alametifarikası var mı?\r\n\r\nTarih boyunca benzeri görülmemiş kazanımlar elde etmemize rağmen mutluluk seviyemizde neden kayda değer bir artış olmadı?\r\n\r\n*Tüm bunları anlamak için tek yapmamız gereken geriye dönüp bakmak ve Homo sapiens’in aslında ne olduğunu, hümanizmin nasıl dünyaya hakim bir din hâline geldiğini ve hümanizm rüyasını gerçekleştirmeye çalışmanın aslında neden insanlığın kendi sonunu getireceğini incelemektir. İşte bu kitabın temel meselesi budur.*\r\n\r\n*Okurken hem eğlenecek hem de çok şaşıracaksınız. Her şeyin ötesinde, kendinizi daha önce hiç düşünmediğiniz şeyleri düşünürken bulacaksınız.*\r\n\r\n- Daniel Kahneman, Hızlı ve Yavaş Düşünme’nin yazarı\r\n\r\n*Homo Deus’u okuduğunuzda uzun ve zorlu bir yolculuğun ardından vardığınız bir uçurumun kenarında durduğunuzu hissedeceksiniz. Yolculuğun artık bir önemi kalmayacak, çünkü bir sonraki adımınızı engin bir boşluğa atacaksınız.*",
                            CreatedDate = new DateTime(2024, 1, 17, 13, 17, 53, 893, DateTimeKind.Local).AddTicks(3967),
                            ImageUrl = "homo-deus-yarinin-kisa-bir-tarihi.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = false,
                            ModifiedDate = new DateTime(2024, 1, 17, 13, 17, 53, 893, DateTimeKind.Local).AddTicks(3967),
                            Name = "Homo Deus: Yarının Kısa Bir Tarihi",
                            PageCount = 308,
                            Price = 60m,
                            Stock = 28,
                            Url = "homo-deus-yarinin-kisa-bir-tarihi-2"
                        },
                        new
                        {
                            Id = 3,
                            Abstract = "Edebiyat tarihinin ilk distopyası olan Efendi Uyanıyor bir 19. yy. centilmeni olan Graham’ın öyküsünü anlatıyor. Nadir görülen bir uykusuzluk hastalığından mustarip olan Graham en sonunda uyumayı başarır. Ne var ki bu kez 200 yıllık trans halinde bir uykuya dalacaktır. Uyandığında ise, banka hesabına işleyen faizler sayesinde dünyanın en zengin ve en güçlü adamı olduğunu öğrenir. O artık bambaşka ve hiç tanımadığı bir dünyada yaşamaktadır. Dünyanın tek efendisi ve sahibi odur! Graham uyuduğu sırada servetini idare eden Konsey, tüm gezegene hüküm süren son derece karanlık ve acımasız bir sistem kurmuştur. Oysa insanların bir kurtarıcı olarak gördüğü Graham’dan beklenen, toplumu bu korkunç despotlardan kurtarmasıdır. Bir distopya klasiği ve politik bilimkurgu türünün en iyi örneklerinden biri olan Wells’in bu başyapıtı, okuru fantastik bir maceraya sürüklüyor. Günümüzden 114 yıl önce yazılmış olmasına rağmen global şirketlerin yükselişi, uçakların seyahat amaçlı kullanımı ve birçok teknolojik gelişmeyi zamanının çok ötesinde başarılı bir şekilde tahmin etmiş olması şaşkınlık yaratıyor. Geleceğe dair yerinde tahminlerinin yanı sıra toplumsal adaletsizlikle boğuşan bir dünyayı tasvir eden Efendi Uyanıyor, distopya, bilim kurgu ve politik roman hayranları için mükemmel bir seçim. \"Wells’in en çarpıcı yönü, edebiyatın klişeleşmiş yanlarına yeni bir soluk getirip canlılık katması...\" -The Spectator- \"Politik bilim-kurgu ve distopya severler için kaçırılmaması gereken bir eser...\" -Times Literary Supplement-",
                            CreatedDate = new DateTime(2024, 1, 17, 13, 17, 53, 893, DateTimeKind.Local).AddTicks(3969),
                            ImageUrl = "efendi-uyaniyor.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = true,
                            ModifiedDate = new DateTime(2024, 1, 17, 13, 17, 53, 893, DateTimeKind.Local).AddTicks(3969),
                            Name = "Efendi Uyanıyor",
                            PageCount = 417,
                            Price = 85m,
                            Stock = 39,
                            Url = "efendi-uyaniyor-3"
                        },
                        new
                        {
                            Id = 4,
                            Abstract = "Milliways Öğlen Menüsü, editörünün iznini alarak, Otostopçunun Galaksi Rehberi’nden bir pasaj aktarmaktaydı. Pasaj şöyleydi: Belli başlı her galaktik uygarlığın tarihi üç ayrı ve fark edilebilir aşamadan geçme eğilimindedir. Bu aşamalar Hayatta Kalma, Sorgulama ve İncelikli Düşünmedir; bir başka deyişle Nasıl, Neden ve Nerede aşamaları olarak da bilinirler. Örneğin, ilk aşama Nasıl Yiyebiliriz? sorusuyla, ikinci aşama Neden Yiyoruz? sorusuyla, üçüncü aşamaysa Öğle Yemeğini Nerede Yiyelim? sorusuyla tanımlanmaktadır.\r\n\r\nMenü daha sonra Milliways’in, Evrenin Sonundaki Restoran’ın bu üçüncü soruya çok uygun ve seçkin bir cevap olduğunu söylüyordu.\r\n\r\nAltın Kalp’in yolcuları sabahtan itibaren altı tamamen imkânsız işi başarmışken, günü gerçekten layık olduğu bir şekilde taçlandırmaya karar vermişlerdi: Gidilebilecek en iyi restoranda, seyredilebilecek en iyi manzaraya karşı mükellef bir yemek.\r\n\r\nBu arada gidiyoruz, ama aranızda rezervasyon yaptıran oldu mu?",
                            CreatedDate = new DateTime(2024, 1, 17, 13, 17, 53, 893, DateTimeKind.Local).AddTicks(3971),
                            ImageUrl = "evrenin-sonundaki-restoran.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = false,
                            ModifiedDate = new DateTime(2024, 1, 17, 13, 17, 53, 893, DateTimeKind.Local).AddTicks(3971),
                            Name = "Evrenin Sonundaki Restoran",
                            PageCount = 444,
                            Price = 90m,
                            Stock = 13,
                            Url = "evrenin-sonundaki-restoran-4"
                        },
                        new
                        {
                            Id = 5,
                            Abstract = "Ray Bradbury sadece bilimkurgunun değil fantastik edebiyatın ve korkunun da yirminci yüzyıldaki ustalarından biri. Bilimkurgunun *iyi edebiyat* da olabileceğini kanıtlayan belki de ilk yazar. Yayımlandığı anda klasikleşen, distopya edebiyatının dört temel kitabından biri olan Fahrenheit 451 ise bir yirminci yüzyıl başyapıtı.\r\n\r\nGuy Montag bir itfaiyeciydi. Televizyonun hüküm sürdüğü bu dünyada kitaplar ise yok olmak üzereydi zira itfaiyeciler yangın söndürmek yerine ortalığı ateşe veriyordu. Montag’ın işi ise yasadışı olanların en tehlikelisini yakmaktı: Kitapları.\r\n\r\nMontag yaptığı işi tek bir gün dahi sorgulamamıştı ve tüm gününü televizyonla kaplı odalarda geçiren eşi Mildred’la beraber yaşıyordu. Ancak yeni komşusu Clarisse’le tanışmasıyla tüm hayatı değişti. Kitapların değerini kavramaya başlayan Montag artık tüm bildiklerini sorgulayacaktı.\r\n\r\nİnsanların uğruna canlarını feda etmeyi göze aldığı bu kitapların içinde ne vardı?\r\nGerçeklerin farkına vardıktan sonra bu karanlık toplumda artık yaşanabilir miydi?\r\n\r\nFahrenheit 451, yeryüzünde tek bir kitap kalacak olsa, o kitap olmaya aday.",
                            CreatedDate = new DateTime(2024, 1, 17, 13, 17, 53, 893, DateTimeKind.Local).AddTicks(3972),
                            ImageUrl = "fahrenheit-451.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = true,
                            ModifiedDate = new DateTime(2024, 1, 17, 13, 17, 53, 893, DateTimeKind.Local).AddTicks(3973),
                            Name = "Fahrenheit 451",
                            PageCount = 307,
                            Price = 60m,
                            Stock = 28,
                            Url = "fahrenheit-451-5"
                        },
                        new
                        {
                            Id = 6,
                            Abstract = "1984 kitabı, İngiliz filozof ve yazar George Orwell tarafından kaleme alınmış, 1984 kitap konusu olarak 20. yüzyılın en önemli distopya örneklerinden biri olmuştur. George Orwell, 1948 yılında tamamladığı ve geleceğe dair karamsar bir kurgu geliştirerek gelecek hakkında insanlığı uyarmayı amaçlamıştır. Egemen sınıfa dayalı, totaliter, baskıcı bir yönetim anlayışının benimsendiği üç ayrı devletin egemenliğindeki siyasal düzenden bahsetmektedir. 1984 kitabı, günümüz ile geçmiş arasında gerçekçi bir benzerliklere dayandıran, dönemin okurlarını düşündürtüp hayal güçlerinin sınırlarını zorlamayı sağlayan distopik, alegorik, politik bir romandır.",
                            CreatedDate = new DateTime(2024, 1, 17, 13, 17, 53, 893, DateTimeKind.Local).AddTicks(3974),
                            ImageUrl = "bindokuzyuzseksendort-1984.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = true,
                            ModifiedDate = new DateTime(2024, 1, 17, 13, 17, 53, 893, DateTimeKind.Local).AddTicks(3974),
                            Name = "1984",
                            PageCount = 485,
                            Price = 95m,
                            Stock = 16,
                            Url = "bindokuzyuzseksendort-1984-6"
                        },
                        new
                        {
                            Id = 7,
                            Abstract = "H. G. Wells, bilimkurgunun atası, türe adını altın harflerle yazdırmış en büyük yazarlardan. Yazdığı bilim fantazileri nesiller boyu yazarları etkilemiş, onlara yol göstermiş; ilk basıldıkları dönemden itibaren etkilerini yitirmeden okurların gönlünde taht kurmaya devam etmiştir. Görünmez Adam da Wells’in eserleri içinde en akılda kalıcı olanlardan biri.\r\n\r\nTuhaf görünüşlü yabancı, bir tipi sırasında Iping Köyü’ne gelir. Garip hareketleri, giyinişi, suratının tamamının bandajlar içinde olması ve gözlüklerini bir an olsun gözünden çıkarmaması köy sakinleri tarafından kimi zaman şüpheyle, kimi zaman düşmanca karşılanır. Kısa süre içerisinde hakkındaki dedikodular giderek yoldan çıkan bir dizi olaya neden olacaktır.",
                            CreatedDate = new DateTime(2024, 1, 17, 13, 17, 53, 893, DateTimeKind.Local).AddTicks(3975),
                            ImageUrl = "gorunmez-adam.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = false,
                            ModifiedDate = new DateTime(2024, 1, 17, 13, 17, 53, 893, DateTimeKind.Local).AddTicks(3976),
                            Name = "Görünmez Adam",
                            PageCount = 139,
                            Price = 55m,
                            Stock = 19,
                            Url = "gorunmez-adam-7"
                        },
                        new
                        {
                            Id = 8,
                            Abstract = "Hayvan Çiftliği ya da orijinal ismiyle \"Animal Farm\", Eric Arthur Blair yani kitaplarını yazarken kullandığı ismiyle George Orwell’in mecazi bir dille kaleme aldığı ve ilk kez 1945 yılında Birleşik Krallık’ta yayımlan, 1996 tarihinde de Retro Hugo Ödülü’nü kazanan, fabl tarzındaki siyasi hiciv romanıdır. Stalinizmin eleştirildiği \"Hayvan Çiftliği\" romanı, SSCB’nin kuruluşundan itibaren meydana gelen önemli olayları kara mizah yoluyla anlatmaktadır. Yayımlandığında büyük bir ilgi uyandıran bu eser 1954 ve 1999 yıllarında filme uyarlanmış, Pink Floyd’un Animals albümüne ilham olmuştur. George Orwell’in tarihsel bir gerçeği eleştirdiği “Hayvan Çiftliği” eseri, Türkçeye ilk kez 1954 yılında çevrilmiştir.\r\n\r\nGeorge Orwell (25 Haziran 1903 - 21 Ocak 1950), asıl ismi Eric Arthur Blair olan ve oluşturduğu Big Brother (Büyük Birader) kavramı ile tanınan, gazetecilik ve eleştirmenlik de yapmış 20. yüzyıl İngiliz edebiyatının önde gelen yazarıdır. Kaleme aldığı eserleri birçok dile çevrilen, çağdaş klasikler arasında gösterilen George Orwell, “Hayvan Çiftliği” eserinde bir devrimin trajedisini dile getirmiştir.",
                            CreatedDate = new DateTime(2024, 1, 17, 13, 17, 53, 893, DateTimeKind.Local).AddTicks(3977),
                            ImageUrl = "hayvan-ciftligi.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = true,
                            ModifiedDate = new DateTime(2024, 1, 17, 13, 17, 53, 893, DateTimeKind.Local).AddTicks(3978),
                            Name = "Hayvan Çiftliği",
                            PageCount = 99,
                            Price = 45m,
                            Stock = 26,
                            Url = "hayvan-ciftligi-8"
                        },
                        new
                        {
                            Id = 9,
                            Abstract = "Bir hedef bulacaksınız, o uğurda çalışacaksınız, hedefinizi gerçekleştirmek için bir yol arayacaksınız, yol yoksa da o yolu yapacaksınız. Bir defa geçtiğiniz yoldan da bir daha geri dönmeyeceksiniz. Çünkü lüzumsuz geri dönüş başarısızlıktır, tekrara düşmektir, ufku kapatmaktır. Hedef bulmak, yol açmak ve aynı yoldan geri dönmemek… Hayattaki gayemiz budur.",
                            CreatedDate = new DateTime(2024, 1, 17, 13, 17, 53, 893, DateTimeKind.Local).AddTicks(3979),
                            ImageUrl = "insan-gelecegini-nasil-kurar.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = true,
                            ModifiedDate = new DateTime(2024, 1, 17, 13, 17, 53, 893, DateTimeKind.Local).AddTicks(3979),
                            Name = "İnsan Geleceğini Nasıl Kurar",
                            PageCount = 420,
                            Price = 119m,
                            Stock = 13,
                            Url = "insan-gelecegini-nasil-kurar-9"
                        },
                        new
                        {
                            Id = 10,
                            Abstract = "*Bu satırları okuyanlarınızın büyük çoğunluğunun, insanların bir mitten ibaret olduğuna inandığını biliyorum ama ben size onların gerçekten var olduklarını bildirmek üzere buradayım. Bilmeyenler için söyleyeyim, insan dediğimiz şey orta zekâlı ve iki ayaklı bir yaşam formu; evrenin çok ıssız bir köşesinde yer alan küçük ve sulu bir gezegende, büyük ölçüde yanılsamalarla dolu bir varoluş sürdürüyor.*\r\n\r\nYağmurlu bir akşamda Profesör Andrew Martin, önce dünyanın en büyük matematik bilmecesini çözmeyi başarıyor, ardından sırra kadem basıyor. Nihayet bir yol kenarında çırılçıplak halde bulunduğunda, kıyafetsizlikten daha ciddi bir meselesi olduğu ortaya çıkıyor: Andrew Martin artık insanlardan tiksiniyor; görünüşlerinden de yiyip içtiklerinden de bitmeyen şiddet ve savaş arzularından da... Yabancı bir tür arasında kaybolmuş hissediyor kendini. Sevgi ve aile kavramları onda şaşırtıcı bir ilgi uyandırsa da tüm sakinlerinden nefret ediyor bu gezegenin. Newton hariç... Ama o da bir köpek işte...",
                            CreatedDate = new DateTime(2024, 1, 17, 13, 17, 53, 893, DateTimeKind.Local).AddTicks(3981),
                            ImageUrl = "insanlar.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = true,
                            ModifiedDate = new DateTime(2024, 1, 17, 13, 17, 53, 893, DateTimeKind.Local).AddTicks(3981),
                            Name = "İnsanlar",
                            PageCount = 216,
                            Price = 75m,
                            Stock = 40,
                            Url = "insanlar-10"
                        },
                        new
                        {
                            Id = 11,
                            Abstract = "Charlotte Perkins Gilman yaşadığı dönemin önde gelen hümanistlerinden ve kadın hakları savunucularından biri olmasının yanında feminist edebiyatın en önemli erken dönem temsilcilerinden. Yazıldıktan yaklaşık 65 sene sonra kitap formatında yayımlanabilen Kadınlar Ülkesi ise feminist ütopyanın ilk örneklerinden.\r\n\r\nBirinci Dünya Savaşı’nın arifesinde üç Amerikalı erkek pek fazla insanın bulunmadığı, ücra bir yerde, tamamen kadınlardan oluşan bir topluluğa denk gelir. Gözlerine inanamayan kâşifler bu topraklarda erkeklerin de olması gerektiğine dair inançlarıyla araştırmalarına başlar.\r\n\r\nÇok geçmeden bu gizemli ülke ile ilgili gerçekler bir bir açığa çıksa da misafirlerin merakı giderilmenin aksine daha da artar ve Kadınlar Ülkesi’nin yönetim biçiminden inançlarına, kültüründen ekonomisine ve hatta anneliğe kadar pek çok konuda bilgi sahibi olmaya ve toplumsal cinsiyet rollerini sorgulamaya başlarlar.\r\n\r\nToplumsal roller cinsiyete göre belirlenebilir mi? Kadınlık ve erkeklik değişmez kavramlar mıdır?\r\n\r\nKadınlar Ülkesi, ataerkilliğe verilmiş nüktedan bir yanıt.",
                            CreatedDate = new DateTime(2024, 1, 17, 13, 17, 53, 893, DateTimeKind.Local).AddTicks(3982),
                            ImageUrl = "kadinlar-ulkesi.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = true,
                            ModifiedDate = new DateTime(2024, 1, 17, 13, 17, 53, 893, DateTimeKind.Local).AddTicks(3983),
                            Name = "Kadınlar Ülkesi",
                            PageCount = 315,
                            Price = 65m,
                            Stock = 25,
                            Url = "kadinlar-ulkesi-11"
                        },
                        new
                        {
                            Id = 12,
                            Abstract = "2016 yılının BBC Reith derslerinde Stephen Hawking, bütün bir ömür süren araştırmalarını on beş dakika içinde aktarma gibi gerçekten zorlu bir meydan okumayı kabul etti. Bu çok kısa süren derslerde Hawking, evrenin gizemlerini ortaya sererken, kara delikleri anladığımız takdirde uzayzamanın sırlarına erişebileceğimizi vurguluyor.",
                            CreatedDate = new DateTime(2024, 1, 17, 13, 17, 53, 893, DateTimeKind.Local).AddTicks(3984),
                            ImageUrl = "kara-delikler.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = false,
                            ModifiedDate = new DateTime(2024, 1, 17, 13, 17, 53, 893, DateTimeKind.Local).AddTicks(3984),
                            Name = "Kara Delikler",
                            PageCount = 439,
                            Price = 90m,
                            Stock = 4,
                            Url = "kara-delikler-12"
                        },
                        new
                        {
                            Id = 13,
                            Abstract = "\"Kumarbaz\" tüm varlığını, gücünü, yeteneğini rulet masasına yatıran; bilinmeyene, tehlikeye özlem duyan; hem başkaldıran, hem korkan; içinde binbir türlü çelişki barındıran kumara tutkun bir adamın romanı. Kendisi de bir süre kumarın tutsağı olan Dostoyevski, belki hiçbir romanına kendi yaşamından bu kadar çok şey katmamıştır. Hiçbir şey yazmasaydı bile \"Kumarbaz\" onu Dostoyevski yapmaya yeterdi.",
                            CreatedDate = new DateTime(2024, 1, 17, 13, 17, 53, 893, DateTimeKind.Local).AddTicks(3986),
                            ImageUrl = "kumarbaz.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = false,
                            ModifiedDate = new DateTime(2024, 1, 17, 13, 17, 53, 893, DateTimeKind.Local).AddTicks(3986),
                            Name = "Kumarbaz",
                            PageCount = 417,
                            Price = 85m,
                            Stock = 10,
                            Url = "kumarbaz-13"
                        },
                        new
                        {
                            Id = 14,
                            Abstract = " “Son” denilen nükleer felaketten sonra anne ve oğul arasında kurulan geçmişi ve o günü kapsayan ancak sınırları olan bir ilişkinin kapısından içeri girerken; ilacın, elektriğin, kalabalığın, cep telefonlarının ve günümüze ait hiçbir gerecin olmadığı bir dünyaya adım atacaksınız. Hayatta kalma güdüsü, yalnızlık\r\nve ölüm temalarıyla öne çıkan, Galceye özgü akıcı ve güçlü tasvirlerle ilerleyen Nebo’nun Mavi Kitabı; günümüz insanının doğadan ne kadar kopuk yaşadığını da  gözler önüne seriyor.\r\n \r\nManon Steffan Ros “ekolojik distopya” temeline dayanan,\r\nödüllü ve çoksatan romanında, insanın hayatta kalma içgüdüsüyle birlikte, çağdaş dünya düzenini de sorguluyor.",
                            CreatedDate = new DateTime(2024, 1, 17, 13, 17, 53, 893, DateTimeKind.Local).AddTicks(3987),
                            ImageUrl = "nebonun-mavi-kitabi.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = true,
                            ModifiedDate = new DateTime(2024, 1, 17, 13, 17, 53, 893, DateTimeKind.Local).AddTicks(3988),
                            Name = "Nebo'nun Mavi Kitabı",
                            PageCount = 582,
                            Price = 115m,
                            Stock = 29,
                            Url = "nebonun-mavi-kitabi-14"
                        },
                        new
                        {
                            Id = 15,
                            Abstract = "Ey Türk gençliği! Birinci görevin, Türk bağımsızlığını, Türk Cumhuriyeti’ni sonsuza kadar korumak ve savunmaktır. Varlığının ve geleceğinin tek temeli budur. Bu temel, senin en değerli hazinendir. Gelecekte de, seni bu hazineden yoksun bırakmak isteyecek iç ve dış düşmanların olacaktır. Bir gün, bağımsızlık ve cumhuriyeti savunma zorunluluğuna düşersen, göreve atılmak için, içinde bulunacağın durumun olanak ve koşullarını düşünmeyeceksin!",
                            CreatedDate = new DateTime(2024, 1, 17, 13, 17, 53, 893, DateTimeKind.Local).AddTicks(3989),
                            ImageUrl = "nutuk.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = true,
                            ModifiedDate = new DateTime(2024, 1, 17, 13, 17, 53, 893, DateTimeKind.Local).AddTicks(3989),
                            Name = "Nutuk",
                            PageCount = 332,
                            Price = 65m,
                            Stock = 34,
                            Url = "nutuk-15"
                        },
                        new
                        {
                            Id = 16,
                            Abstract = "Çoğu çalışma insanlığın serüvenini ya tarihi ya da biyolojik bir yaklaşımla ele alır, ancak Harari 70 bin yıl önce gerçekleşen Bilişsel Devrim’le başlattığı bu kitabında gelenekleri yerle bir ediyor. İnsanların küresel ekosistemde oynadıkları rolden imparatorlukların yükselişine ve modern dünyaya kadar pek çok konuyu irdeleyen Sapiens, tarihle bilimi bir araya getirerek kabul görmüş anlatıları yeniden ele alıyor. Harari ayrıca geleceğe bakmaya da zorluyor okuru. Yakın zamanda insanlar, dört milyar yıldır yaşama hükmeden doğal seçilim yasalarını esnetmeye başladılar. Artık sadece dünyayı değil, kendimizi ve diğer canlıları tasarlama becerisi de kazandık. Peki bu bizi nereye götürüyor, bizi neye dönüştürebilir?",
                            CreatedDate = new DateTime(2024, 1, 17, 13, 17, 53, 893, DateTimeKind.Local).AddTicks(3991),
                            ImageUrl = "hayvanlardan-tanrilara-sapiens.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = true,
                            ModifiedDate = new DateTime(2024, 1, 17, 13, 17, 53, 893, DateTimeKind.Local).AddTicks(3991),
                            Name = "Hayvanlardan Tanrılara Sapiens",
                            PageCount = 639,
                            Price = 160m,
                            Stock = 32,
                            Url = "hayvanlardan-tanrilara-sapiens-16"
                        },
                        new
                        {
                            Id = 17,
                            Abstract = "Savaş ve Barış, gençlere dünya klasiklerini tanıtarak, onları bu eserleri okumaya yönlendirmek amacıyla hazırladığımız Arkadaş Dünya Klasikleri Gençlik Özet Dizisi’nin üçüncü kitabıdır. Genç okurların kolayca anlayarak beğeniyle okuyabileceği yalın bir Türkçeyle orijinal metinden uyarlanmıştır.\r\n\r\nTolstoy’un başyapıtı olan Savaş ve Barış, dünya edebiyatının en önemli eserlerindendir ve Milli Eğitim Bakanlığınca 100 Temel eser kapsamında öğrencilere tavsiye edilmiştir.",
                            CreatedDate = new DateTime(2024, 1, 17, 13, 17, 53, 893, DateTimeKind.Local).AddTicks(3992),
                            ImageUrl = "savas-ve-baris.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = true,
                            ModifiedDate = new DateTime(2024, 1, 17, 13, 17, 53, 893, DateTimeKind.Local).AddTicks(3992),
                            Name = "Savaş ve Barış",
                            PageCount = 239,
                            Price = 85m,
                            Stock = 14,
                            Url = "savas-ve-baris-14"
                        },
                        new
                        {
                            Id = 18,
                            Abstract = "Kaç Ömür Gerek, Yaşamayı Öğrenmek İçin?\r\n\r\nTom Hazard’ın tehlikeli bir sırrı var. 41 yaşında sıradan bir tarih öğretmeni gibi göru¨nse de nadir rastlanan bir hastalık yu¨zu¨nden aslında yu¨zyıllardır hayatta. Shakespeare’le aynı sahnede yer almış, Kaptan Cook’la açık denizleri fethetmiş, Fitzgerald’larla içki içmiş. Ama şimdi, tek istediği normal bir hayat su¨rmek. Kimliğini değiştirmeye devam ettiği su¨rece geçmişini geride bırakabilir ve hayatta kalabilir.\r\n\r\nYapmaması gereken tek bir şey var, aşık olmak.",
                            CreatedDate = new DateTime(2024, 1, 17, 13, 17, 53, 893, DateTimeKind.Local).AddTicks(3994),
                            ImageUrl = "zamani-durdurmanin-yollari.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = true,
                            ModifiedDate = new DateTime(2024, 1, 17, 13, 17, 53, 893, DateTimeKind.Local).AddTicks(3994),
                            Name = "Zamanı Durdurmanın Yolları",
                            PageCount = 329,
                            Price = 80m,
                            Stock = 5,
                            Url = "zamani-durdurmanin-yollari-15"
                        },
                        new
                        {
                            Id = 19,
                            Abstract = "*Yaşamla ölüm arasında bir kütüphane var,* dedi. *Bu kütüphanedeki raflar sonsuza kadar gider.  Her kitap yaşamış olabileceğin başka bir hayatı yaşama şansını sunar sana. Farklı seçimler yapmış olsan, şu an nasıl bir hayatın olacağını görürsün…\r\nPişmanlıklarını telafi etme şansın olsaydı, bazı konularda farklı davranır mıydın?*\r\n\r\nNora Seed berbat halde. Kedisi öldü. İşinden kovuldu. Abisi onunla konuşmuyor. Kimsenin ona ihtiyacı yok. Art arda alınmış kötü kararların sonucunda bir kütüphanede buluyor kendini. Zamanın hiç akmadığı bir gece yarısı kütüphanesinde, sonsuz sayıda kitabın ortasında... Kitapların her birinde Nora’nın farklı bir hayatı yazılı. Başka kararlar verseydi yaşamış olabileceği hayatlar.\r\n\r\nFarklı kariyerler, farklı eşler, farklı arkadaşlar, farklı şehirler arasında gidip gelen Nora’nın aklı sorularla doluyor. Mutluluk sadece önemli sandığımız seçimlerde mi gizli? Yanlış giden her detayın sorumlusu gerçekten biz miyiz? Hayatı yaşanılır kılan ne? Yanlış bir karar insanın tüm hayatına mal olabilir mi?",
                            CreatedDate = new DateTime(2024, 1, 17, 13, 17, 53, 893, DateTimeKind.Local).AddTicks(3995),
                            ImageUrl = "gece-yarisi-kutuphanesi.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = true,
                            ModifiedDate = new DateTime(2024, 1, 17, 13, 17, 53, 893, DateTimeKind.Local).AddTicks(3996),
                            Name = "Gece Yarısı Kütüphanesi",
                            PageCount = 512,
                            Price = 100m,
                            Stock = 32,
                            Url = "gece-yarisi-kutuphanesi-16"
                        },
                        new
                        {
                            Id = 20,
                            Abstract = "Dünyayı pençesine almış bir delilik salgını...\r\n\r\nKonuşma yoluyla, zihinden zihne bulaşarak yayılan bir hastalık...\r\n\r\nYıkılmanın eşiğine gelmiş uygarlık...\r\n\r\nVaktiyle bu amansız hastalık üzerine çalışmış eski dilbilimci Murat Siyavuş, umutsuzluk içinde annesinin evine sığınmıştır. Acımasız bir devlet kurumunun peşine düştüğünü öğrenince, evden çıkıp hayata karışmak ve salgının dönüştürdüğü dünyayla yüzleşmek zorunda kalır.",
                            CreatedDate = new DateTime(2024, 1, 17, 13, 17, 53, 893, DateTimeKind.Local).AddTicks(3997),
                            ImageUrl = "sicak-kafa.jpg",
                            IsActive = true,
                            IsDeleted = false,
                            IsHome = true,
                            ModifiedDate = new DateTime(2024, 1, 17, 13, 17, 53, 893, DateTimeKind.Local).AddTicks(3997),
                            Name = "Sıcak Kafa",
                            PageCount = 285,
                            Price = 90m,
                            Stock = 40,
                            Url = "sicak-kafa-20"
                        });
                });

            modelBuilder.Entity("BookApp.Models.Entities.Concrete.BookCategory", b =>
                {
                    b.Property<int>("BookId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("BookId", "CategoryId");

                    b.ToTable("BookCategories", (string)null);

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            CategoryId = 5
                        },
                        new
                        {
                            BookId = 1,
                            CategoryId = 10
                        },
                        new
                        {
                            BookId = 2,
                            CategoryId = 13
                        },
                        new
                        {
                            BookId = 2,
                            CategoryId = 4
                        },
                        new
                        {
                            BookId = 3,
                            CategoryId = 5
                        },
                        new
                        {
                            BookId = 3,
                            CategoryId = 1
                        },
                        new
                        {
                            BookId = 3,
                            CategoryId = 10
                        },
                        new
                        {
                            BookId = 4,
                            CategoryId = 5
                        },
                        new
                        {
                            BookId = 4,
                            CategoryId = 1
                        },
                        new
                        {
                            BookId = 4,
                            CategoryId = 10
                        },
                        new
                        {
                            BookId = 5,
                            CategoryId = 5
                        },
                        new
                        {
                            BookId = 5,
                            CategoryId = 10
                        },
                        new
                        {
                            BookId = 5,
                            CategoryId = 3
                        },
                        new
                        {
                            BookId = 6,
                            CategoryId = 5
                        },
                        new
                        {
                            BookId = 6,
                            CategoryId = 10
                        },
                        new
                        {
                            BookId = 6,
                            CategoryId = 3
                        },
                        new
                        {
                            BookId = 7,
                            CategoryId = 5
                        },
                        new
                        {
                            BookId = 7,
                            CategoryId = 1
                        },
                        new
                        {
                            BookId = 8,
                            CategoryId = 5
                        },
                        new
                        {
                            BookId = 8,
                            CategoryId = 10
                        },
                        new
                        {
                            BookId = 8,
                            CategoryId = 3
                        },
                        new
                        {
                            BookId = 9,
                            CategoryId = 7
                        },
                        new
                        {
                            BookId = 9,
                            CategoryId = 8
                        },
                        new
                        {
                            BookId = 9,
                            CategoryId = 12
                        },
                        new
                        {
                            BookId = 10,
                            CategoryId = 5
                        },
                        new
                        {
                            BookId = 10,
                            CategoryId = 1
                        },
                        new
                        {
                            BookId = 10,
                            CategoryId = 10
                        },
                        new
                        {
                            BookId = 11,
                            CategoryId = 5
                        },
                        new
                        {
                            BookId = 11,
                            CategoryId = 1
                        },
                        new
                        {
                            BookId = 11,
                            CategoryId = 10
                        },
                        new
                        {
                            BookId = 12,
                            CategoryId = 2
                        },
                        new
                        {
                            BookId = 12,
                            CategoryId = 9
                        },
                        new
                        {
                            BookId = 12,
                            CategoryId = 6
                        },
                        new
                        {
                            BookId = 13,
                            CategoryId = 5
                        },
                        new
                        {
                            BookId = 13,
                            CategoryId = 10
                        },
                        new
                        {
                            BookId = 13,
                            CategoryId = 11
                        },
                        new
                        {
                            BookId = 14,
                            CategoryId = 5
                        },
                        new
                        {
                            BookId = 14,
                            CategoryId = 1
                        },
                        new
                        {
                            BookId = 14,
                            CategoryId = 10
                        },
                        new
                        {
                            BookId = 15,
                            CategoryId = 13
                        },
                        new
                        {
                            BookId = 15,
                            CategoryId = 14
                        },
                        new
                        {
                            BookId = 16,
                            CategoryId = 13
                        },
                        new
                        {
                            BookId = 16,
                            CategoryId = 4
                        },
                        new
                        {
                            BookId = 17,
                            CategoryId = 5
                        },
                        new
                        {
                            BookId = 17,
                            CategoryId = 10
                        },
                        new
                        {
                            BookId = 18,
                            CategoryId = 5
                        },
                        new
                        {
                            BookId = 18,
                            CategoryId = 10
                        },
                        new
                        {
                            BookId = 19,
                            CategoryId = 5
                        },
                        new
                        {
                            BookId = 19,
                            CategoryId = 1
                        },
                        new
                        {
                            BookId = 19,
                            CategoryId = 10
                        },
                        new
                        {
                            BookId = 20,
                            CategoryId = 1
                        },
                        new
                        {
                            BookId = 20,
                            CategoryId = 3
                        },
                        new
                        {
                            BookId = 20,
                            CategoryId = 5
                        });
                });

            modelBuilder.Entity("BookApp.Models.Entities.Concrete.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 1, 17, 13, 17, 53, 893, DateTimeKind.Local).AddTicks(2941),
                            Description = "Genel kategorisine giren ve kategorisiz kalan kitaplar",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2024, 1, 17, 13, 17, 53, 893, DateTimeKind.Local).AddTicks(2956),
                            Name = "Genel",
                            Url = "Genel"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 1, 17, 13, 17, 53, 893, DateTimeKind.Local).AddTicks(2980),
                            Description = "Bilim Kurgu Kitapları",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2024, 1, 17, 13, 17, 53, 893, DateTimeKind.Local).AddTicks(2981),
                            Name = "Bilim Kurgu",
                            Url = "bilim-kurgu"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 1, 17, 13, 17, 53, 893, DateTimeKind.Local).AddTicks(2982),
                            Description = "Bilim ve Mühendislik Kitapları",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2024, 1, 17, 13, 17, 53, 893, DateTimeKind.Local).AddTicks(2982),
                            Name = "Bilim ve Mühendislik",
                            Url = "bilim-ve-muhendislik"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2024, 1, 17, 13, 17, 53, 893, DateTimeKind.Local).AddTicks(2984),
                            Description = "Distopya Kitapları",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2024, 1, 17, 13, 17, 53, 893, DateTimeKind.Local).AddTicks(2984),
                            Name = "Distopya",
                            Url = "distopya"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2024, 1, 17, 13, 17, 53, 893, DateTimeKind.Local).AddTicks(2985),
                            Description = "Dünya Tarihi Kitapları",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2024, 1, 17, 13, 17, 53, 893, DateTimeKind.Local).AddTicks(2985),
                            Name = "Dünya Tarihi",
                            Url = "dunya-tarihi"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2024, 1, 17, 13, 17, 53, 893, DateTimeKind.Local).AddTicks(2986),
                            Description = "Edebiyat Kitapları",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2024, 1, 17, 13, 17, 53, 893, DateTimeKind.Local).AddTicks(2986),
                            Name = "Edebiyat",
                            Url = "edebiyat"
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2024, 1, 17, 13, 17, 53, 893, DateTimeKind.Local).AddTicks(2987),
                            Description = "Fizik Kitapları",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2024, 1, 17, 13, 17, 53, 893, DateTimeKind.Local).AddTicks(2988),
                            Name = "Fizik",
                            Url = "fizik"
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2024, 1, 17, 13, 17, 53, 893, DateTimeKind.Local).AddTicks(2988),
                            Description = "İnsan ve Toplum Kitapları",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2024, 1, 17, 13, 17, 53, 893, DateTimeKind.Local).AddTicks(2989),
                            Name = "İnsan ve Toplum",
                            Url = "insan-ve-toplum"
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2024, 1, 17, 13, 17, 53, 893, DateTimeKind.Local).AddTicks(2990),
                            Description = "Kişisel Kitapları",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2024, 1, 17, 13, 17, 53, 893, DateTimeKind.Local).AddTicks(2990),
                            Name = "Kişisel Gelişim",
                            Url = "kisisel-gelisim"
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2024, 1, 17, 13, 17, 53, 893, DateTimeKind.Local).AddTicks(2991),
                            Description = "Popüler Bilim Kitapları",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2024, 1, 17, 13, 17, 53, 893, DateTimeKind.Local).AddTicks(2991),
                            Name = "Popüler Bilim",
                            Url = "populer-bilim"
                        },
                        new
                        {
                            Id = 11,
                            CreatedDate = new DateTime(2024, 1, 17, 13, 17, 53, 893, DateTimeKind.Local).AddTicks(2992),
                            Description = "Romanlar",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2024, 1, 17, 13, 17, 53, 893, DateTimeKind.Local).AddTicks(2992),
                            Name = "Roman",
                            Url = "roman"
                        },
                        new
                        {
                            Id = 12,
                            CreatedDate = new DateTime(2024, 1, 17, 13, 17, 53, 893, DateTimeKind.Local).AddTicks(2994),
                            Description = "Rus Edebiyatı Kitapları",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2024, 1, 17, 13, 17, 53, 893, DateTimeKind.Local).AddTicks(2994),
                            Name = "Rus Edebiyatı",
                            Url = "rus-edebiyati"
                        },
                        new
                        {
                            Id = 13,
                            CreatedDate = new DateTime(2024, 1, 17, 13, 17, 53, 893, DateTimeKind.Local).AddTicks(2996),
                            Description = "Söyleşi Kitapları",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2024, 1, 17, 13, 17, 53, 893, DateTimeKind.Local).AddTicks(2996),
                            Name = "Söyleşi",
                            Url = "soylesi"
                        },
                        new
                        {
                            Id = 14,
                            CreatedDate = new DateTime(2024, 1, 17, 13, 17, 53, 893, DateTimeKind.Local).AddTicks(2997),
                            Description = "Tarih Kitapları",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2024, 1, 17, 13, 17, 53, 893, DateTimeKind.Local).AddTicks(2997),
                            Name = "Tarih",
                            Url = "tarih"
                        },
                        new
                        {
                            Id = 15,
                            CreatedDate = new DateTime(2024, 1, 17, 13, 17, 53, 893, DateTimeKind.Local).AddTicks(2998),
                            Description = "Türkiye Tarihi Kitapları",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2024, 1, 17, 13, 17, 53, 893, DateTimeKind.Local).AddTicks(2998),
                            Name = "Türkiye Tarihi",
                            Url = "turkiye-tarihi"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
